DROP DATABASE IF EXISTS STORES_db;

CREATE DATABASE STORES_db;

USE STORES_db;

CREATE TABLE department(
  id INT NOT NULL AUTO_INCREMENT,
  name  VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE role(
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL NOT NULL,
  department_id INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE employee(
 id  INT NOT NULL AUTO_INCREMENT,
 first_name VARCHAR(30) NULL,
 last_name  VARCHAR(30) NULL,
 role_id   INT,
 manager_id INT,
 PRIMARY KEY (id)
 );


